# Generated by Django 4.1.3 on 2022-12-07 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('rating', models.CharField(choices=[('PG', 'Pg'), ('PG-13', 'Pg13'), ('R', 'R'), ('NC-17', 'Nc17'), ('G', 'Default')], default='G', max_length=20)),
                ('synopsis', models.TextField(default=None)),
                ('user', models.ManyToManyField(related_name='movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
