# Generated by Django 4.1.4 on 2022-12-07 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_remove_movie_added_by_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.AddField(
            model_name='movie',
            name='added_by',
            field=models.ManyToManyField(related_name='movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
