# Generated by Django 4.1.4 on 2022-12-07 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0005_remove_movie_user_movie_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='added_by',
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(null=True, related_name='movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
