# Generated by Django 4.1.4 on 2022-12-08 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_remove_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ManyToManyField(related_name='movie', to=settings.AUTH_USER_MODEL),
        ),
    ]
