# Generated by Django 4.1.4 on 2022-12-08 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_movie_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_order', to='movies.movie'),
        ),
    ]
