# Generated by Django 4.1.4 on 2022-12-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_order_buyed_by_alter_order_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='title',
            new_name='movie',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buyed_by',
            new_name='user',
        ),
    ]
